version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    networks:
      default:
    ports:
      - '5432:5432'
